[package]
name = "shift_binary_csr"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
prover = { workspace = true, features = ["prover"] }
verifier_generator = { workspace = true }
common_constants = {workspace = true }
circuit_common = {workspace = true }
serde = { workspace = true }
serde_json = "*"

[features]
witness_eval_fn = []
